language: python
python:
  - 2.7
  - 3.3
  - 3.5
addons:
  apt:
    packages:
      - libcairo2-dev
before_install:
 - pip install coveralls
script:
 - python setup.py test
 - python -m coverage run --source=./shabam setup.py test
after_success:
 - coveralls
